import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { handleRequest } from '../lib/http.ts';
import { Store } from '../lib/store.ts';

const origin = 'http://127.0.0.1:3040';
test('actual record routes enforce roles, Origin, upload bounds, selected variants, receipts, and report isolation', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'carevault-record-http-'));
  const store = new Store(dir);
  t.after(() => { store.close(); rmSync(dir, { recursive: true, force: true }); });
  const request = (path: string, method = 'GET', body?: string | Uint8Array, headers: Record<string,string> = {}) => handleRequest(new Request(origin + path, {method, headers: {Origin: origin,...headers}, ...(body === undefined ? {} : {body: typeof body === 'string' ? body : new Uint8Array(body)})}), store);
  const login = async (role:'patient'|'developer') => {
    const response = await request('/api/session','POST',JSON.stringify(store.credentials.demoAccounts![role]),{'Content-Type':'application/json'});
    assert.equal(response.status,200); return response.headers.get('set-cookie')!.split(';')[0];
  };
  const patient = await login('patient'), developer = await login('developer');
  const uploadHeaders = {'Content-Type':'application/pdf','X-File-Name':'Private%20report.pdf',Cookie:patient};
  const input = '%PDF-1.4\nHTTP upload fixture, not real OCR';
  assert.equal((await request('/api/patient/records','POST',input,{...uploadHeaders,Cookie:developer})).status,403);
  assert.equal((await request('/api/patient/records','POST',input,{...uploadHeaders,Origin:'https://elsewhere.test'})).status,403);
  assert.equal((await request('/api/patient/records','POST',input,{...uploadHeaders,'Content-Length':String(21*1024*1024)})).status,413);
  assert.equal((await request('/api/patient/records','POST',new Uint8Array(20*1024*1024+1),uploadHeaders)).status,413);
  assert.equal((await request('/api/patient/records','POST','<html>',uploadHeaders)).status,400);
  const upload = await request('/api/patient/records','POST',input,uploadHeaders);
  assert.equal(upload.status,201); const record=await upload.json();
  assert.equal(store.all('document').length,1);
  assert.equal((await request(`/api/patient/records/${record.id}/files/original`,'GET',undefined,{Cookie:developer})).status,403);
  const file = await request(`/api/patient/records/${record.id}/files/original`,'GET',undefined,{Cookie:patient});
  assert.equal(await file.text(),input); assert.equal(file.headers.get('cache-control'),'no-store, private'); assert.equal(file.headers.get('content-type'),'application/pdf');
  assert.equal((await request(`/api/patient/records/${record.id}/files/redacted`,'GET',undefined,{Cookie:patient})).status,409);
  const grant={connected:true,allowReports:true,records:{[record.id]:{text:true,redacted:false,original:false}}};
  assert.equal((await request('/api/patient/apps/scan-review','PUT',JSON.stringify(grant),{Cookie:patient,'Content-Type':'application/json'})).status,200);
  const auth={Authorization:`Bearer ${store.credentials.integrationTokens['scan-review']}`};
  assert.equal((await request(`/api/v2/records/${record.id}/files/original`,'GET',undefined,auth)).status,403);
  writeFileSync(join(dir,'documents',record.id,'extracted.txt'),'Private Name');
  writeFileSync(join(dir,'documents',record.id,'redacted.txt'),'[REDACTED]');
  store.put('document',record.id,{...record,status:'ready'});
  const text=await request(`/api/v2/records/${record.id}/text`,'GET',undefined,auth);
  assert.equal(await text.text(),'[REDACTED]'); const receipt=text.headers.get('x-carevault-receipt'); assert.ok(receipt);
  const list=await (await request('/api/v2/records','GET',undefined,auth)).json();
  assert.equal(list.records.length,1); assert.equal(list.records[0].title,undefined);
  const report=await request('/api/v2/reports','POST',JSON.stringify({title:'Report',body:'Unverified test report',sourceReceiptIds:[receipt]}),{...auth,'Content-Type':'application/json'});
  assert.equal(report.status,201); const saved=await report.json();
  assert.equal((await request(`/api/v2/records/${saved.id}/files/original`,'GET',undefined,auth)).status,403);
  await request('/api/patient/apps/scan-review/revoke','POST','{}',{Cookie:patient,'Content-Type':'application/json'});
  assert.equal((await request(`/api/v2/records/${record.id}/text`,'GET',undefined,auth)).status,403);
});
